# Generated by Django 4.0.6 on 2022-08-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('paragrafo', models.CharField(max_length=255)),
            ],
        ),
    ]
